version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      # The Anthropic API key needs to be provided here
      # You can create a .env file in the same directory as this docker-compose.yml
      # and add the line: ANTHROPIC_API_KEY=your_actual_api_key
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=${PORT:-3001}
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./:/app
      # Use a named volume for node_modules instead of a bind mount
      - node_modules:/app/node_modules

volumes:
  redis_data:
  node_modules: